name: ml-scoring
channels:
  - conda-forge
  - defaults
dependencies:
  - ansi2html=1.6.0
  - anyio=3.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - bottleneck=1.3.2
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - confuse=1.5.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - dash=1.21.0
  - dash-core-components=1.17.1
  - dash-html-components=1.1.4
  - dash-renderer=1.9.1
  - dash-table=4.12.0
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flask=2.0.1
  - flask-compress=1.10.1
  - freetype=2.10.4
  - future=0.18.2
  - htmlmin=0.1.12
  - idna=3.1
  - imagehash=4.2.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-dash=0.4.0
  - jupyter_client=7.0.2
  - jupyter_core=4.7.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.1
  - jupyterlab_widgets=1.0.2
  - kaleido-core=0.2.1
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - mathjax=2.7.7
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - msys2-conda-epoch=20160418
  - multimethod=1.4
  - nbclassic=0.3.1
  - nbclient=0.5.4
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.6.2
  - notebook=6.4.3
  - numba=0.54.0
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandas-profiling=3.0.0
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - patsy=0.5.1
  - phik=0.11.2
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.2.4
  - plotly=5.3.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - pycparser=2.20
  - pydantic=1.8.2
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-kaleido=0.2.1
  - python_abi=3.9
  - pytz=2021.1
  - pywavelets=1.1.1
  - pywin32=301
  - pywinpty=1.1.4
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - retrying=1.3.3
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shap=0.39.0
  - six=1.16.0
  - slicer=0.0.7
  - sniffio=1.2.0
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tangled-up-in-unicode=0.1.0
  - tbb=2021.3.0
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.1.0
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - ucrt=10.0.20348.0
  - urllib3=1.26.6
  - vc=14.2
  - visions=0.7.1
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - alembic==1.7.1
    - autopage==0.4.0
    - category-encoders==2.2.2
    - cliff==3.9.0
    - cmaes==0.8.2
    - cmd2==2.2.0
    - colorlog==6.4.1
    - greenlet==1.1.1
    - imbalanced-learn==0.8.0
    - imblearn==0.0
    - mako==1.1.5
    - mlxtend==0.19.0
    - optuna==2.9.1
    - pbr==5.6.0
    - prettytable==2.2.0
    - pyperclip==1.8.2
    - pyreadline3==3.3
    - sqlalchemy==1.4.23
    - stevedore==3.4.0
    - xgboost==1.4.2
    - xlrd==2.0.1
